<div class="span12">
	<div class="widget round">
		<ul class="more-image">
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k02.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k02.jpg" alt="tech-image 1" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k03.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k03.jpg" alt="tech-image 1" /><span>this is a test photo</span></a> </li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k04.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k04.jpg" alt="tech-image 1" /><span>this is a test photo</span></a> </li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k05.jpeg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k05.jpeg" alt="tech-image 1" /><span>this is a test photo</span></a> </li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k06.jpeg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k06.jpeg" alt="tech-image 1" /><span>this is a test photo</span></a> </li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k07.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k07.jpg" alt="tech-image 2" /><span>this is a test photo</span></a> </li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k08.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k08.jpg" alt="tech-image 3" /><span>this is a test photo</span></a></li> 
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k09.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k09.jpg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k10.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k10.jpg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k11.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k11.jpg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k12.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k12.jpg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k13.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k13.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k14.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k14.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k15.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k15.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k16.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k16.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k17.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k17.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k18.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k18.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k19.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k19.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k20.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k20.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k21.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k21.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k22.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k22.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k23.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k23.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k24.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k24.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k25.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k25.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k26.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k26.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k27.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k27.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k28.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k28.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k29.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k29.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k30.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k30.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k31.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k31.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k32.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k32.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
			<li><a href="<?php echo Yii::app()->baseUrl ?>/image/k33.jpg" title="add a caption to title attribute / or leave blank" class="thickbox" rel="lightbox[tech]"><img src="<?php echo Yii::app()->baseUrl ?>/image/k33.jpeg" alt="tech-image 4" /><span>this is a test photo</span></a></li>
		</ul>

	</div>
</div>